### ISSUE TITLE
Asking general question does not return an answer.

### ISSUE THREAD

**Issue by MrRKernelPanic** [MycroftAI/fallback-wolfram-alpha#37]
e.g. How tall is mount everest

returns
~~~~| INFO     |   607 | QuestionsAnswersSkill | Timeout occured check responses
~~~~| INFO     |   607 | Skill Recommendations Fallback | fallback-wolfram-alpha
~~~~croft_skills_manager | Best match (1.0): fallback-wolfram-alpha by mycroftai
  ^--- NEWEST ---^ 

but then replies with 'I'm not sure I understand'.

I am running 
***********************************************************************
** Picroft enclosure platform version: Buster Keaton - Pork Pi
**                       mycroft-core: 20.2.4 ( master )
***********************************************************************

I'm a little new to this, what additonal information can i provide?

**Comment by krisgesling** [comment]
Hi Mark, Mycroft should be able to answer this and it seems that it's selecting the Wolfram Alpha Skill correctly so something else must be happening. Can you check the skills.log which is located at `/var/log/mycroft/skills.log`?

If you need a hand looking through that log file and are happy to share its contents openly you can run the following command:
```
cat /var/log/mycroft/skills.log | nc termbin.com 9999
```

This will upload it to termbin.com and return a url that you can paste here. Otherwise you can email the link or the file itself to support@mycroft.ai and we can take a look.

Thanks for reporting the issue.

**Comment by MrRKernelPanic** [comment]
Thank you for the feedback on this, it did start working.  I don't think I changed anything other than reboot the unit and logout / back into the website.  I think I probably went a bit bonkers and installed too many skills straight off the bat in keen-ness.  I'm still working through them.

**Comment by krisgesling** [comment]
Glad you're liking it and thanks for reporting anyway. Will keep an eye out and see if we can reproduce it.
